spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: UserService
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: TaskService
          uri: lb://TASK-SERVICE
          predicates:
            - Path=/task/**



server:
  port: 8888
