spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: UserService
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: TaskService
          uri: lb://TASK-SERVICE
          predicates:
            - Path=/task/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # URL du Discovery Server
    register-with-eureka: false
    fetch-registry: true

server:
  port: 8888
